### ISSUE TITLE
How to actually install it? :(

### ISSUE THREAD

**Issue by ghost** [supaboss/nobara-dotfiles#1]
Hey! Sorry, I'm using Linux for the first time and I really love your setup, but I don't understand how to install, what I should to do after I'm cloning your repo. I have clean Nobara install.

**Comment by slashedzer0** [comment]
hello! can you tell me which Nobara variant are you using? official/vanilla? (the official comes with pre-installed extensions)

**Comment by ghost** [comment]
> hello! can you tell me which Nobara variant are you using? official/vanilla? (the official comes with pre-installed extensions)

I'm using GNOME vanilla version

**Comment by slashedzer0** [comment]
okay, firstly, you have to install all the extensions in this dotfiles' readme (see 'Extensions' section) 

then, install gnome tweaks, by running: 
`sudo dnf install gnome-tweaks`

(basically, gnome tweaks is used to change themes, fonts, icons, and stuff)

after that, (still on readme) under 'Desktop Setup' section, download all the necessary files (themes, fonts, icons)

paste them into their respective directories:
themes goes to ~/.themes
font goes to ~/.fonts
icons goes to ~/.icons

( ~ is home directory, if you still confused, google it -- also, if the directories mentioned above is not present, you can create them manually)

if everything goes right, all of them will be listed on gnome tweaks menu.

now, assuming the theme, fonts, icons are correctly applied, clone this repo:

inside .themes directory, there are two gnome-shell themes: float and mod, copy one of them to ~/.themes, then open up gnome tweaks and change the shell theme to the theme you just copied -- (the one in the screenshots are float)

finally, this is the most important part...
go to preset directory, there are multiple extensions presets,but i strongly recommend to use the latest one, 

load the extensions preset by running:
`dconf load /org/gnome/shell/extensions/ < extensions-latest.conf`

please make sure to **install all the extensions** before running the command above!

then, logout, and re-login session.

**Comment by ghost** [comment]
Thanks!
